# Generated by Django 2.2.4 on 2019-10-02 04:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlegb', models.CharField(default='', max_length=512)),
                ('url_img_gb', models.URLField(default='', max_length=2000)),
                ('namegb', models.CharField(blank=True, default='', max_length=50)),
                ('pricegb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('urlgb', models.URLField(blank=True, default='', max_length=2000)),
                ('urlgb_patocinado', models.URLField(blank=True, default='', max_length=2000)),
                ('titlebg', models.CharField(blank=True, default='', max_length=512)),
                ('namebg', models.CharField(blank=True, default='', max_length=50)),
                ('url_img_bg', models.URLField(blank=True, default='', max_length=2000)),
                ('pricebg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('urlbg', models.URLField(blank=True, default='', max_length=2000)),
                ('urlbg_patocinado', models.URLField(blank=True, default='', max_length=2000)),
                ('namedx', models.CharField(blank=True, default='', max_length=50)),
                ('pricedx', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('urldx', models.URLField(blank=True, default='', max_length=2000)),
                ('urldx_patocinado', models.URLField(blank=True, default='', max_length=2000)),
                ('namein', models.CharField(blank=True, default='', max_length=50)),
                ('pricein', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('urlin', models.URLField(blank=True, default='', max_length=2000)),
                ('urlin_patocinado', models.URLField(blank=True, default='', max_length=2000)),
                ('namemz', models.CharField(blank=True, default='', max_length=50)),
                ('pricemz', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('urlmz', models.URLField(blank=True, default='', max_length=2000)),
                ('urlmz_patocinado', models.URLField(blank=True, default='', max_length=2000)),
                ('best_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('best_url', models.URLField(blank=True, default='', max_length=2000)),
                ('best_name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Xiaomi_bg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlebg', models.CharField(default='', max_length=512)),
                ('namebg', models.CharField(blank=True, default='', max_length=50)),
                ('url_img_bg', models.URLField(default='', max_length=2000)),
                ('pricebg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('urlbg', models.URLField(blank=True, default='', max_length=2000)),
            ],
        ),
    ]
