# Generated by Django 2.2.4 on 2019-09-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='titlebg',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='url_img_bg',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
