# Generated by Django 2.2.4 on 2019-09-16 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0002_auto_20190916_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaomi',
            name='price_best',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
