# Generated by Django 2.2.4 on 2019-09-16 16:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0006_auto_20190916_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='price_best',
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='pricemz',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=10),
        ),
    ]
