# Generated by Django 2.2.4 on 2019-09-16 16:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0008_auto_20190916_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='pricemz',
            field=models.DecimalField(decimal_places=3, default=Decimal('10.000'), max_digits=20),
        ),
    ]
