# Generated by Django 2.2.4 on 2019-09-16 16:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0009_auto_20190916_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='pricemz',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20),
        ),
    ]
