# Generated by Django 2.2.4 on 2019-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0010_auto_20190916_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='pricemz',
            field=models.DecimalField(decimal_places=2, default='10000.00', max_digits=20),
        ),
    ]
