# Generated by Django 2.2.4 on 2019-09-16 19:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0014_auto_20190916_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='pricebg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='pricedx',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='pricegb',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='pricein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='pricemz',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
