# Generated by Django 2.2.4 on 2019-09-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0017_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
