# Generated by Django 2.2.4 on 2019-09-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='price_best',
        ),
    ]
