# Generated by Django 2.2.4 on 2019-09-20 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0019_remove_xiaomi_price_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaomi',
            name='best_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
