# Generated by Django 2.2.4 on 2019-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0020_xiaomi_best_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaomi',
            name='best_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='best_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
