# Generated by Django 2.2.4 on 2019-09-22 22:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0022_xiaomi_real_dolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
        ),
    ]
