# Generated by Django 2.2.4 on 2019-09-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0023_dolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='real_dolar',
        ),
    ]
